import { StyleSheet } from 'react-native';

const StylesHomeScreen = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'#020123'
    },
    areaVersus:{
        alignSelf:'center',
        alignItems:'center',
        height:244,
        width:358,
        borderRadius:40,
        padding:10,
        backgroundColor:'#020123',
        margin:2
    },
    linearArea:{
        justifyContent:'center',
        alignItems:'center',
        alignSelf:'center',
        borderRadius:40,
        marginTop:25,
        height:248,
        width:362,
    },
    areaTitle:{
        height:40
    },
    textTitle:{
        fontSize:21,
        fontWeight:'bold',
        color:'#fff',
        marginBottom:20
    },
    areaTextVersus:{
        flex:1,
        justifyContent:'center',
        margin:5,
    },  
    textVersus:{
        color:'#fff',
        alignSelf:'center',
        textAlign:'center'
    },
    areaButtons:{
        flexDirection:'row',
        width:362,
        justifyContent:'space-evenly',
        alignItems:'center',
        alignSelf:'center',
        marginVertical:30
    },  
    Buttons:{
        width:46,
        height:46,
        borderRadius:22,
    },
    linearGradient : { 
        flex:1, 
        width:46,
        height:46,
        borderRadius:22,

        justifyContent:'center',
        alignItems:'center'
    },
    areaNotes:{
        backgroundColor:'#fff',
        height:'100%',
        borderTopLeftRadius:50,
        borderTopRightRadius:50,
        marginTop:50
    },
    notesHeader:{
        flexDirection:'row',
        justifyContent:'space-between',
        padding:15
    },
    notesHeaderText:{
        width:'70%',
        paddingLeft:10
    },
    titleNotes:{
        fontSize:19,
        fontWeight:'bold',
        color:'#AE0A9E',
        marginBottom:4
    },
    dateNotes:{
        color:'rgba(174,10,158,0.45)',
        fontSize:15,
        fontStyle:'italic'
    },
    areaButtonNote:{
        justifyContent:'center',
        alignItems:'center',
        marginRight:10
    },
    areaNote:{
        height:130 
    },
    areaScroll:{
        paddingHorizontal:22
    },
    textNote:{
        textAlign:'justify',
        color:'#272499',
        fontSize:15,
        lineHeight:22
    },
    imageButtons:{
        width:28,
        height:28,
        alignSelf:'center'
    },
    imagHeader:{
        width:30,
        height:30,
        marginRight:15
    }
});

export default StylesHomeScreen;

